{
 "title": "Main Dashboard",
 "description": "Dashboard per la visualizzazione di varie tipologie di sensori dislocati in una città",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cella",
    "label": "Seleziona cella",
    "query": "SELECT DISTINCT cella\nFROM (\n    SELECT cella FROM innovacity.temperatures where $__timeFilter(timestamp)\n    UNION ALL\n    SELECT cella FROM innovacity.humidity where $__timeFilter(timestamp)\n    UNION ALL\n    SELECT cella FROM innovacity.chargingStations where $__timeFilter(timestamp)\n    UNION ALL\n    SELECT cella FROM innovacity.ecoIslands where $__timeFilter(timestamp)\nUNION ALL\n    SELECT cella FROM innovacity.waterPresence where $__timeFilter(timestamp)\nUNION ALL\n    SELECT cella FROM innovacity.dust_PM10 where $__timeFilter(timestamp)\nUNION ALL\n    SELECT cella FROM innovacity.electricalFault where $__timeFilter(timestamp)\n)"
   },
   {
    "name": "tmp_sensors_id",
    "label": "Sensori di temperatura",
    "query": "select distinct ID_sensore from innovacity.temperatures WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "umd_sensors_id",
    "label": "Sensori di umidità",
    "query": "select distinct ID_sensore from innovacity.humidity WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "ecoIs_sensors_id",
    "label": "Sensori isole ecologiche",
    "query": "select distinct ID_sensore from innovacity.ecoIslands WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "colRic_sensors_id",
    "label": "Colonnine di ricarica",
    "query": "select distinct ID_sensore from innovacity.chargingStations WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "wp_sensors_id",
    "label": "Sensori presenza acqua",
    "query": "select distinct ID_sensore from innovacity.waterPresence WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "dstPM10_sensors_id",
    "label": "Sensori polveri sottili PM10",
    "query": "select distinct ID_sensore from innovacity.dust_PM10 WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   },
   {
    "name": "eltcF_sensors_id",
    "label": "Sensori guasti elettrici",
    "query": "select distinct ID_sensore from innovacity.electricalFault WHERE cella IN ($Cella) AND $__timeFilter(timestamp)"
   }
  ]
 },
 "panels": [
  { "title": "City Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT cella, argMax(value,timestamp) from innovacity.healthScore group by cella"
    }
   ]
  },
  {
   "title": "Mappa dei sensori",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 15, "w": 14, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n     argMax(value, timestamp) as value,\r\n    'Termometro' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.temperatures\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n   CASE\r\n        WHEN argMax(value, timestamp) = 0 THEN 'Libera'\r\n        WHEN argMax(value, timestamp) = 1 THEN 'Occupata'\r\n        ELSE NULL\r\n    END as value,\r\n      CASE\r\n        WHEN value = 'Libera' THEN 0\r\n        WHEN value = 'Occupata' THEN 100\r\n        ELSE NULL\r\n    END as color_picker,\r\n    'Colonnina di ricarica' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.chargingStations\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n      CASE\r\n        WHEN argMax(value, timestamp) = 0 THEN 'Nessuna rilevazione'\r\n        WHEN argMax(value, timestamp) = 1 THEN 'Rilevata Acqua'\r\n        ELSE NULL\r\n    END as value,\r\n      CASE\r\n        WHEN value = 'Nessuna rilevazione' THEN 0\r\n        WHEN value = 'Rilevata Acqua' THEN 100\r\n        ELSE NULL\r\n    END as color_picker,\r\n    'Sensore presenza acqua' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.waterPresence\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n      argMax(value, timestamp) as value,\r\n    'Igrometro' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.humidity\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n   CASE\r\n        WHEN argMax(value, timestamp) = 0 THEN 'Nessun guasto'\r\n        WHEN argMax(value, timestamp) = 1 THEN 'Guasto rilevato'\r\n        ELSE NULL\r\n    END as value,\r\n      CASE\r\n        WHEN value = 'Nessun guasto' THEN 0\r\n        WHEN value = 'Guasto rilevato' THEN 100\r\n        ELSE NULL\r\n    END as color_picker,\r\n    'Sensore guasto elettrico' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.electricalFault\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n     argMax(value, timestamp) as value,\r\n    'Isola ecologica' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.ecoIslands\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n     argMax(value, timestamp) as value,\r\n    'Polveri sottili' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.dust_PM10\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    }
   ]
  },
  {
   "title": "Punteggio di salute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n   avg( score.value)\r\nFROM\r\n    innovacity.healthScore score\r\nJOIN (\r\n    SELECT\r\n        MAX(timestamp) AS max_timestamp,\r\n        cella\r\n    FROM\r\n        innovacity.healthScore\r\n    GROUP BY\r\n        cella\r\n) last_timestamps ON score.cella = last_timestamps.cella AND score.timestamp = last_timestamps.max_timestamp\r\nwhere cella In (${Cella})\r\n"
    }
   ]
  },
  { "title": "Lista allerte", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 } },
  { "title": "Dati Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as tmp_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.temperatures\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as tmp_sensors_id , cella as Cella from innovacity.temperatures"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "description": "Temperatura nel tempo",
   "gridPos": { "h": 9, "w": 17, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore,\r\n    avg(value) as value,\r\n    $__timeInterval(timestamp) as timestamp\r\nFROM \r\n    innovacity.temperatures\r\n    WHERE\r\n    $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore in (${tmp_sensors_id})\r\nGROUP BY \r\n    ID_sensore, timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Temperatura media ",
   "type": "stat",
   "description": "temperatura media nell'intervallo temporale selezionato",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(value) as avgTemperature\nFROM innovacity.temperatures\nWHERE ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND  cella IN ($Cella) AND ID_sensore IN ($tmp_sensors_id);\n"
    }
   ]
  },
  { "title": "Dati umidità", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as umd_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.humidity\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as umd_sensors_id , cella as Cella from innovacity.humidity"
    }
   ]
  },
  {
   "title": "Umidità media",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  avg(value) as avgUmdity\r\nFROM innovacity.humidity\r\nWHERE  $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore IN ($umd_sensors_id);\r\n"
    }
   ]
  },
  {
   "title": "Umidità",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore,\r\n    avg(value) as value,\r\n    $__timeInterval(timestamp) as timestamp\r\nFROM \r\n    innovacity.humidity\r\n    WHERE\r\n    $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore in (${umd_sensors_id})\r\nGROUP BY \r\n    ID_sensore, timestamp;\r\n"
    }
   ]
  },
  { "title": "Polveri sottili", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as dstPM10_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.dust_PM10\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as dstPM10_sensors_id , cella as Cella from innovacity.dust_PM10"
    }
   ]
  },
  {
   "title": "Polveri sottili",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore,\r\n    avg(value) as value,\r\n    $__timeInterval(timestamp) as timestamp\r\nFROM \r\n    innovacity.dust_PM10\r\n    WHERE\r\n    $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore in (${dstPM10_sensors_id})\r\nGROUP BY \r\n    ID_sensore, timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Polveri sottili media",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "conmgNm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  avg(value) as avgPM10\r\nFROM innovacity.dust_PM10\r\nWHERE  $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore IN ($dstPM10_sensors_id);\r\n"
    }
   ]
  },
  { "title": "Isole ecologiche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as ecoIs_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.ecoIslands\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as ecoIs_sensors_id , cella as Cella from innovacity.ecoIslands"
    }
   ]
  },
  {
   "title": "Isole ecologiche",
   "type": "timeseries",
   "description": "Stato di riempimento isole ecologiche",
   "gridPos": { "h": 9, "w": 14, "x": 3, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore,\r\n    avg(value) as value,\r\n    $__timeInterval(timestamp) as timestamp\r\nFROM \r\n    innovacity.ecoIslands\r\n    WHERE\r\n    $__timeFilter(timestamp) AND cella IN ($Cella) AND ID_sensore IN ($ecoIs_sensors_id)\r\nGROUP BY \r\n    ID_sensore, timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Stato riempimento attuale",
   "type": "gauge",
   "description": "Mostra l'ultimo valore dello stato di rimepimento percentuale",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    eco.ID_sensore,\r\n    eco.value,\r\n    eco.timestamp\r\nFROM\r\n    innovacity.ecoIslands eco\r\nJOIN (\r\n    SELECT\r\n        ID_sensore,\r\n        MAX(timestamp) AS max_timestamp\r\n    FROM\r\n        innovacity.ecoIslands\r\n    WHERE ID_sensore IN ($ecoIs_sensors_id) AND cella in ($Cella)\r\n    GROUP BY\r\n        ID_sensore\r\n) last_timestamps ON eco.ID_sensore = last_timestamps.ID_sensore AND eco.timestamp = last_timestamps.max_timestamp;\r\n"
    }
   ]
  },
  { "title": "Sensori di presenza acqua", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as wp_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.waterPresence\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as wp_sensors_id , cella as Cella from innovacity.waterPresence"
    }
   ]
  },
  {
   "title": "Sensori di soglia non attivi:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*) as numeroAcquaRilevata\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n        argMax(value,timestamp) AS last_value\r\n    FROM innovacity.waterPresence\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($wp_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 0\r\n"
    }
   ]
  },
  {
   "title": "Sensori di soglia attivi:",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*) as numeroAcquaRilevata\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n        argMax(value,timestamp) AS last_value\r\n    FROM innovacity.waterPresence\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($wp_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 1\r\n"
    }
   ]
  },
  {
   "title": "Sensori di livello acqua",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 57 },
   "targets": [
    {
     "rawSql": "    SELECT\r\n        ID_sensore,\r\n        argMax(timestamp,timestamp) as \"Data ultima misurazione\",\r\n        argMax(value,timestamp) AS \"Ultimo valore\"\r\n    FROM innovacity.waterPresence\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($wp_sensors_id)\r\n    GROUP BY (ID_sensore)"
    }
   ]
  },
  { "title": "Colonnine di ricarica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as colRic_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.chargingStations\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as colRic_sensors_id , cella as Cella from innovacity.chargingStations"
    }
   ]
  },
  {
   "title": "Colonnine libere",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n    ID_sensore,\r\n    argMax(value,timestamp) AS last_value\r\n    FROM innovacity.chargingStations\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($colRic_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 0 \r\n"
    }
   ]
  },
  {
   "title": "Colonnine occupate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n    argMax(value,timestamp) AS last_value\r\n    FROM innovacity.chargingStations\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($colRic_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 1\r\n"
    }
   ]
  },
  {
   "title": "Colonnine di ricarica",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 66 },
   "targets": [
    {
     "rawSql": "    SELECT\r\n        ID_sensore,\r\n        argMax(timestamp,timestamp) as \"Data ultima misurazione\",\r\n        argMax(value,timestamp) AS \"Ultimo valore\"\r\n    FROM innovacity.chargingStations\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($colRic_sensors_id)\r\n    GROUP BY (ID_sensore)"
    }
   ]
  },
  {
   "title": "Guasti elettrici",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ID_sensore as eltcF_sensors_id,\r\n    max(timestamp) AS last_timestamp,\r\n    argMax(value, timestamp) AS last_value\r\nFROM \r\n    innovacity.electricalFault\r\nGROUP BY \r\n    ID_sensore\r\n"
    },
    {
     "rawSql": "SELECT distinct ID_sensore as eltcF_sensors_id , cella as Cella from innovacity.electricalFault"
    }
   ]
  },
  {
   "title": "Sistemi elettrici operativi",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n    ID_sensore,\r\n    argMax(value,timestamp) AS last_value\r\n    FROM innovacity.electricalFault\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($eltcF_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 0 \r\n"
    }
   ]
  },
  {
   "title": "Guasti rilevati",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n    argMax(value,timestamp) AS last_value\r\n    FROM innovacity.electricalFault\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($eltcF_sensors_id)\r\n    GROUP BY (ID_sensore)\r\n) last_values\r\nWHERE last_values.last_value = 1\r\n"
    }
   ]
  },
  {
   "title": "Sensori di guasti elettrici",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 75 },
   "targets": [
    {
     "rawSql": "    SELECT\r\n        ID_sensore,\r\n        argMax(timestamp,timestamp) as \"Data ultima misurazione\",\r\n        argMax(value,timestamp) AS \"Ultimo valore\"\r\n    FROM innovacity.electricalFault\r\n    WHERE cella IN ($Cella) AND  $__timeFilter(timestamp) AND ID_sensore IN ($eltcF_sensors_id)\r\n    GROUP BY (ID_sensore)"
    }
   ]
  }
 ]
}