{
 "title": "Innovacity Dashboard",
 "description": "Dashboard per la visualizzazione di varie tipologie di sensori dislocati in una città",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cella",
    "label": "Seleziona cella",
    "query": "SELECT DISTINCT cella\nFROM (\n    SELECT cella FROM innovacity.temperatures\n    UNION ALL\n    SELECT cella FROM innovacity.umidities\n    UNION ALL\n    SELECT cella FROM innovacity.chargingStations\n    UNION ALL\n    SELECT cella FROM innovacity.ecoIslands\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mappa Sensori",
   "type": "geomap",
   "description": "dislocazione geografica dei sensori ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    ID_sensore,\n     argMax(cella, timestamp) as cella_sensore,\n    'Termometro' as Tipo,\n    argMax(latitude, timestamp) AS latitude,\n    argMax(longitude, timestamp) AS longitude\nFROM innovacity.temperatures\nGROUP BY ID_sensore\nHAVING cella_sensore IN ($Cella);\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n    'Igrometro' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.umidities\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n     argMax(cella, timestamp) as cella_sensore,\r\n    'Colonnina di ricarica' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.chargingStations\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    },
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n    argMax(cella, timestamp) as cella_sensore,\r\n    'Isola ecologica' as Tipo,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.ecoIslands\r\nGROUP BY ID_sensore\r\nHAVING cella_sensore IN ($Cella);\r\n"
    }
   ]
  },
  { "title": "Dati Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "description": "Temperatura nel tempo",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n    avgMerge(value) as value,\r\n    timestamp\r\nFROM\r\n    innovacity.temperatures\r\nWHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\nGROUP BY timestamp, ID_sensore\r\n\r\n"
    }
   ]
  },
  {
   "title": "Temperatura media ",
   "type": "stat",
   "description": "temperatura media nell'intervallo temporale selezionato",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avgMerge(value) as avgTemperature\nFROM innovacity.temperatures\nWHERE ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND  cella IN ($Cella);\n"
    }
   ]
  },
  { "title": "Dati umidità", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Umidità media",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  avgMerge(value) as avgUmdity\r\nFROM innovacity.umidities\r\nWHERE ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND cella IN ($Cella);\r\n"
    }
   ]
  },
  {
   "title": "Umidità",
   "type": "timeseries",
   "description": "calcola la temperatura media ogni minuto ",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT ID_sensore,\r\navgMerge(value) as value,\r\ntimestamp\r\nFROM innovacity.umidities\r\nWHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\ngroup by ID_sensore, timestamp\r\n"
    }
   ]
  },
  { "title": "Colonnine di ricarica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Colonnine di ricarica",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    ID_sensore,\r\n    'Colonnina di ricarica' as Tipo,\r\n    last_value(value) AS last_value,\r\n    argMax(latitude, timestamp) AS latitude,\r\n    argMax(longitude, timestamp) AS longitude\r\nFROM innovacity.chargingStations\r\nWHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\nGROUP BY (ID_sensore);\r\n"
    }
   ]
  },
  {
   "title": "Colonnine libere",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n        cella,\r\n        last_value(value) AS last_value\r\n    FROM innovacity.chargingStations\r\n    WHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\n    GROUP BY (ID_sensore,cella)\r\n) last_values\r\nWHERE last_values.last_value = 0 AND cella IN ($Cella);\r\n"
    }
   ]
  },
  {
   "title": "Colonnine occupate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*)\r\nFROM (\r\n    SELECT\r\n        ID_sensore,\r\n        cella,\r\n        last_value(value) AS last_value\r\n    FROM innovacity.chargingStations\r\n    WHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\n    GROUP BY (ID_sensore,cella)\r\n) last_values\r\nWHERE last_values.last_value = 1 AND cella IN ($Cella);\r\n"
    }
   ]
  },
  { "title": "Isole ecologiche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Isole ecologiche",
   "type": "timeseries",
   "description": "Stato di riempimento isole ecologiche",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT ID_sensore,\r\nvalue,\r\ntimestamp\r\nFROM innovacity.ecoIslands\r\nWHERE cella IN ($Cella) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\r\n"
    }
   ]
  },
  {
   "title": "Stato riempimento attuale",
   "type": "gauge",
   "description": "Mostra l'ultimo valore dello stato di rimepimento percentuale",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n   \r\n    argMax(value, timestamp) AS last_value,\r\n    ID_sensore\r\nFROM \r\n    \"innovacity\".\"ecoIslands\" \r\nGROUP BY \r\n    ID_sensore\r\nHAVING argMax(cella,timestamp) IN ($Cella)"
    }
   ]
  }
 ]
}