apiVersion: 1
groups:
    - orgId: 1
      name: Electrical alert
      folder: Innovacity alerts
      interval: 1m
      rules:
        - uid: e6ae395d-4c04-47b2-a036-c6b7beb1a67a
          title: Guasto elettrico alert
          condition: C
          data:
            - refId: A
              queryType: table
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PDEE91DDB90597936
              model:
                editorType: sql
                format: 1
                intervalMs: 1000
                maxDataPoints: 43200
                meta:
                    builderOptions:
                        columns: []
                        database: ""
                        limit: 1000
                        mode: list
                        queryType: table
                        table: ""
                pluginVersion: 4.0.3
                queryType: table
                rawSql: SELECT ID_sensore,cella, argMax(value,timestamp) from innovacity.electricalFault GROUP BY ID_sensore,cella LIMIT 1000
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: e8b17515-2cf3-43e2-be39-3323fd37af67
          panelId: 44
          noDataState: NoData
          execErrState: Error
          for: 15s
          annotations:
            __dashboardUid__: e8b17515-2cf3-43e2-be39-3323fd37af67
            __panelId__: "44"
            description: Attenzione è stato rilevato un guasto elettrico all'interno della città.
            runbook_url: ""
            summary: Rilevato guasto elettrico
          labels:
            "": ""
          isPaused: false
