apiVersion: 1
datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    database: innovacity
    port: 9000
    server: clickhouse
    tlsSkipVerify: false
  isDefault: true
