FROM python:3.9

# Imposta la directory di lavoro nel container
WORKDIR /app

RUN pip install --upgrade pip && \
    pip install confluent-kafka==2.3.0 clickhouse-connect==0.7.2 faust==1.10.4 pytest==8.0.2 kafka-python==1.4.7 pytest-asyncio==0.23.5 pylint==3.1.0 pytest-cov==4.1.0 requests avro==1.11.3


