name: CI Pipeline

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.pdf'
      - '**.mdj'
      - '**.dot'
      - '**.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    
    - name: Set DOCKER_BUILDKIT to false
      env:
        DOCKER_BUILDKIT: "0"  # Or "false"
      run: |
        echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

    # Only run the remaining steps if changes were detected
    - name: Check for changes and proceed if needed
      run: |
        if [ -z "$(git diff --name-only --cached HEAD)" ]; then
          echo "No relevant files changed, skipping remaining steps."
          exit 0
        fi

    - name: Run tests
      run: |
        docker compose --profile test up kafka test_base_image clickhouse -d
        docker compose --profile test up test

    - name: Copy coverage report from stopped Docker container
      run: |
        docker cp $(docker ps -a -qf "name=tests"):/app/pylint_output.txt ./pylint_output.txt
      
    # docker cp $(docker ps -a -qf "name=tests"):/app/coverage.xml ./coverage.xml
    # - name: Install Coveralls
    #   run: |
    #     pip install coveralls
      
    # - name: Coveralls
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #   uses: coverallsapp/github-action@v2
      
    # - name: Upload coverage reports to Codecov
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #   uses: codecov/codecov-action@v4.0.1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     slug: ByteOps-swe/MVP

    - name: Create Pylint Badge and put in README.md
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    - run: |
        python create_badge.py
      
    - name: "Push README with changed badge to origin"
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        if [[ $(git diff --cached --name-only 'README.md') ]]; then
          git add README.md
          git commit -m "Aggiornato Pylint Badge"
          git push
        else
          echo "No changes to README.md, skipping commit and push."
        fi